static_service_url: http://192.168.0.82:9898
dubbo: 
  #zookeeper-address: 192.168.0.222:2181
  #zookeeper-address: wulinThinkPad:2181
  zookeeper-address: zxq:2181
  application:
    name: platform-cas
    
server:
  context-path: /cas
  port: 8085
  maxThreadSize: 5000

cache: 
  toolkit: 
    host: 192.168.0.49
    port: 6379
    open: false


logon:
  default: 
    appId: hjb-ebmp
    
hibernate:
    show_sql: false
    
freemarker:
    cache: true
    
spring: 
  freemarker: 
    enabled: false
   
spring.boot.admin.url: http://192.168.0.82:9934
management.security.enabled: false

